services:

  nginx-backend:
    ports:
      - "8080:80"

  nginx-frontend:
    ports:
      - "3000:80"

  database:
    ports:
      - "5432:5432"

  php:
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini