server {
    listen 80;

    # Front (Vite build)
    location / {
        root /var/www/frontend;
        try_files $uri /index.html;
    }

    # API Platform
    location /api {
        root /var/www/html/public;
        try_files $uri /index.php$is_args$args;

        location ~ \.php$ {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        }
    }
}
